### ISSUE TITLE
Home: add spacing above View More button on mobile

### ISSUE THREAD

**Issue by glhr** [2030-WebDev/PeopleOfAalborg#9]

**Comment by glhr** [comment]
![81961695_743223089503490_8005928355251617792_n](https://user-images.githubusercontent.com/23728920/71563211-21dad900-2a8c-11ea-9ad0-3a10246e10a2.png)

**Comment by glhr** [comment]
![viewmore](https://user-images.githubusercontent.com/23728920/71563304-8a768580-2a8d-11ea-99c7-4dc6fa4c3192.PNG)

**Comment by Kowalatam** [comment]
Fixed  both issues mentioned here

![image](https://user-images.githubusercontent.com/25955436/73395731-61d9e980-42e0-11ea-9945-6605f16bd7e9.png)

![image](https://user-images.githubusercontent.com/25955436/73395846-8e8e0100-42e0-11ea-86f6-94e61ab72756.png)
